name: Build Windows Executable

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2022  # use uma versão explícita com VS instalado
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: x86_64-pc-windows-msvc
          override: true
      - name: Set up MSVC environment
        uses: ilammy/msvc-dev-cmd@v1
      - name: Build project
        run: cargo build --release --target x86_64-pc-windows-msvc
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: monero-miner
          path: target/x86_64-pc-windows-msvc/release/monero-miner.exe
